/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.*;

import org.junit.Test;

public final class AppTest {

    @Test
    public void appHasAGreeting() {
        // App classUnderTest = new App();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
